small: &small
  agents:
    cluster: builds-fi-2
    queue: monorepo-ci
    size: small

common: &common
  plugins:
  - EmbarkStudios/k8s#1.2.10:
      service-account-name: monorepo-ci
      image: gcr.io/embark-shared/ml/ci-runner@sha256:8943c6b150813cce844a87dd528bed4a997814c9a5302b9562aed76814998dbb
      default-secret-name: buildkite-k8s-plugin
      always-pull: false
  << : *small

steps:
  - group: ":vertical_traffic_light: Validating PR"
    steps:
      - label: ":hourglass: Validating branch age"
        command: bash .buildkite/validate-branch-age.sh
        << : *small

      - label: ":straight_ruler: Checking line-endings"
        command: bash .buildkite/check-line-endings.sh
        << : *small

      - label: ":lock: Checking lockfile"
        command: bash .buildkite/validate-lockfile.sh
        << : *common

  - wait

  - label: 📚 Publish docs
    command: bash .buildkite/publish-docs.sh
    << : *common

  - label: ":python-black: Validate black"
    command: bash .buildkite/run-black.sh
    << : *common

  - label: ":isort: Validate isort"
    command: bash .buildkite/run-isort.sh
    << : *common
