small: &small
  agents:
    cluster: builds-fi-2
    queue: monorepo-ci
    size: small

large: &large
  agents:
    cluster: builds-fi-2
    queue: monorepo-ci
    size: large


plugins: &plugins
  plugins:
  - EmbarkStudios/k8s#1.2.10:
      service-account-name: monorepo-ci
      image: gcr.io/embark-shared/ml/ci-runner@sha256:ca727fde178e60353820416619201cb0302b8896ddeda412916e7aa802fb441d
      default-secret-name: buildkite-k8s-plugin
      always-pull: false

small_container: &small_container
  << : *small
  << : *plugins

large_container: &large_container
  << : *large
  << : *plugins

steps:
  - group: ":passport_control: Validating PR"
    steps:
      - label: ":hourglass: Validating branch age"
        command: bash .buildkite/validate-branch-age.sh
        << : *small

      - label: ":straight_ruler: Checking line-endings"
        command: bash .buildkite/check-line-endings.sh
        << : *small

      - label: ":lock: Checking lockfile"
        command: bash .buildkite/validate-lockfile.sh
        << : *small_container

  - wait

  - group: ":vertical_traffic_light: Validating changes"
    steps:
      - label: 📚 Publish docs
        command: bash .buildkite/publish-docs.sh
        << : *small_container

      - label: ":python-black: Validate black"
        command: bash .buildkite/run-black.sh
        << : *small_container

      - label: ":isort: Validate isort"
        command: bash .buildkite/run-isort.sh
        << : *small_container

      - label: ":bandit: Validate bandit"
        command: bash .buildkite/run-bandit.sh
        << : *small_container

      - label: ":pytest: Run tests"
        command: bash .buildkite/run-pytest.sh
        << : *large_container

  - wait

  - label: ":package: Validate packaging"
    command: bash .buildkite/run-package.sh
    << : *small_container
