name: 'Generate docs'

runs:
  using: "composite"
  steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Tell Pants to use Python 3.10
      shell: bash
      run: |
        echo "PY=python3.10" >> $GITHUB_ENV
        echo "PANTS_PYTHON_INTERPRETER_CONSTRAINTS=['==3.10.*']" >> $GITHUB_ENV

    - name: Initialize Pants
      uses: pantsbuild/actions/init-pants@main
      with:
        # cache0 makes it easy to bust the cache if needed
        gha-cache-key: cache0-py3.10
        named-caches-hash: ${{ hashFiles('locks/*.lock', 'locks/tools/*.lock') }}

    - name: Build docs
      shell: bash
      run: |
        . ci/init.sh no
        pants package //docs:book
