name: Deploy static content to Pages

on:
  push:
    branches: ["main", "luc/test31"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Accept Repository Changes
        run: |
          sudo apt-get --allow-releaseinfo-change update
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.10.4
          architecture: x64
          version: 2.10.1
          prerelease: false
          enable-pep582: true
          cache: true
          cache-dependency-path: '**/pdm.lock'
      - name: Install dependencies
        run: pdm install --plugins && pdm install -d -G ci && pdm torch install cpu
      - name: Build docs
        run: cd docs && make deploy
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: doc-build
          path: 'docs/_build/dirhtml'

  deploy:
    needs: build-docs
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: doc-build
          path: 'docs/_build/dirhtml'
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
