name: Deploy static content to Pages

on:
  push:
    branches: ["main", "luc/test31"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - uses: pdm-project/setup-pdm@v3
        name: Setup PDM
        with:
          python-version: 3.10.0
          architecture: x64
          version: 2.10.1
          prerelease: false
          enable-pep582: true
          cache: true
          cache-dependency-path: '**/pdm.lock'
      - name: Install dependencies
        run: pdm install --plugins && pdm install -d -G ci && pdm torch install cpu
      - name: Build docs
        run: cd docs && make deploy
      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'docs/_build/dirhtml'
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v1
