# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["ts/gh-docs"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - uses: pdm-project/setup-pdm@v3
        name: Setup PDM
        with:
          python-version: 3.8  # Version range or exact version of a Python version to use, the same as actions/setup-python
          architecture: x64    # The target architecture (x86, x64) of the Python interpreter. the same as actions/setup-python
          version: 2.1.5       # The version of PDM to install. Leave it as empty to use the latest version from PyPI, or 'head' to use the latest version from GitHub
          prerelease: true     # Allow prerelease versions to be installed
          enable-pep582: true  # Enable PEP 582 package loading globally
          cache: true
          cache-dependency-path: '**/pdm.lock'
      - name: Install dependencies
        run: pdm install -d -G ci
      - name: Build docs
        run: cd docs && make deploy
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'docs/_build/dirhtml'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
