name: Release
on:
  push:
    tags:
      - v*

jobs:
  create-release:
    name: release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Fetch tags
      run: git fetch --prune --unshallow --tags

    - name: Initialize Pants
      uses: pantsbuild/actions/init-pants@main
      with:
        # cache0 makes it easy to bust the cache if needed
        gha-cache-key: cache0-py3.10
        named-caches-hash: ${{ hashFiles('locks/*.lock', 'locks/tools/*.lock') }}
        pants-python-version: 3.10

    - name: Build Packages
      run: pants package //:package

    - name: "Build Changelog"
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v3.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        configuration: ".github/release-action-config.json"
        toTag: ${{ github.ref }}

    - name: Release to GitHub
      uses: mikepenz/action-gh-release@v0.2.0-a03
      with:
        body: ${{ steps.github_release.outputs.changelog }}
        prerelease: false
        tag_name: ${{ github.ref }}
        name: "Release ${{ github.ref_name }}"
        files: |
          dist/*
          LICENSE-*

    - name: Publish Packages to PyPi
      env:
        PDM_PUBLISH_PASSWORD: ${{ secrets.PYPI_TOKEN }}

      run: pants publish //:package
